apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  # כאן אנחנו שואבים את סוג השירות (LoadBalancer) והפורט
  type: {{ .Values.service.type }}
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80 # הפורט הציבורי שהמשתמשים ייגשו אליו בדפדפן
      targetPort: {{ .Values.service.port }} # הפורט 5000 הפנימי של ה-Flask
